# Generated by Django 6.0.2 on 2026-03-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('food', 'Food'), ('transport', 'Transport'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('health', 'Health'), ('education', 'Education'), ('subscriptions', 'Subscriptions'), ('other', 'Other')], max_length=20),
        ),
    ]
